# Generated by Django 5.0.6 on 2024-06-29 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('Falseid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('social_name', models.CharField(max_length=500)),
                ('cnpj', models.CharField(max_length=14)),
                ('is_active', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_street', models.CharField(blank=True, max_length=200, null=True)),
                ('andress_number', models.CharField(blank=True, max_length=100, null=True)),
                ('andress_neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('andress_city', models.CharField(blank=True, max_length=100, null=True)),
                ('andress_state', models.CharField(blank=True, max_length=2, null=True)),
                ('andress_zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_ate', models.DateTimeField(auto_now_add=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
            },
        ),
    ]
